<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "    <meta name=\"description\" content=\"OpenFLIXR Setup\">\n";
echo "    <meta name=\"author\" content=\"OpenFLIXR\">\n";
echo "    <title>OpenFLIXR Setup</title>\n";
echo "    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n";
echo "    <link href=\"css/stylish-portfolio.css\" rel=\"stylesheet\">\n";
echo "    <link href=\"css/gsdk-base.css\" rel=\"stylesheet\" />\n";
echo "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css\">\n";
echo "\n";
echo "    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n";
echo "    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n";
echo "    <!--[if lt IE 9]>\n";
echo "        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n";
echo "        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n";
echo "    <![endif]-->\n";
echo "\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "    <div class=\"image-container set-full-height\" style=\"background-color: #4c4c4c;\">\n";
echo "        <div class=\"container\">\n";
echo "            <div class=\"row\">\n";
echo "                <div class=\"col-sm-10 col-sm-offset-1\">\n";
echo "                    <div class=\"wizard-container\">\n";
echo "                        <div class=\"card wizard-card ct-wizard-azzure\" id=\"wizard\">\n";
echo "                            <form action=\"settings.php\" method=\"POST\" id=\"registration-form\">\n";
echo "                                <div class=\"wizard-header\">\n";
echo "                                    <h3>OpenFLIXR <b>Setup</b><sup> 1.5</sup<br><br></h3>\n";
echo "                                </div>\n";
echo "                                <ul>\n";
echo "                                    <li><a href=\"#setup\" data-toggle=\"tab\">Info</a></li>\n";
echo "                                    <li><a href=\"#login\" data-toggle=\"tab\">Password</a></li>\n";
echo "                                    <li><a href=\"#network\" data-toggle=\"tab\">Network</a></li>\n";
echo "                                    <li><a href=\"#ssl\" data-toggle=\"tab\">Access</a></li>\n";
echo "                                    <li><a href=\"#usenet\" data-toggle=\"tab\">Usenet</a></li>\n";
echo "                                    <!-- <li><a href=\"#newznab\" data-toggle=\"tab\">Newznab</a></li>-->\n";
echo "                                    <!-- <li><a href=\"#modules\" data-toggle=\"tab\">Modules</a></li>-->\n";
echo "                                    <li><a href=\"#extra\" data-toggle=\"tab\">Extras</a></li>\n";
echo "                                    <li><a href=\"#finish\" data-toggle=\"tab\">Plex</a></li>\n";
echo "                                </ul>\n";
echo "\n";
echo "                                <div class=\"tab-content\">\n";
echo "                                    <div class=\"tab-pane\" id=\"setup\" name=\"messagebox\">\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-12\">\n";
echo "                                                <h4 class=\"info-text\">Welcome to your OpenFLIXR</h4>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-10 col-sm-offset-1\">\n";
echo "                                                <p><span style=\"color: #808080;\">Finish this setup to automatically generate API keys and configure OpenFLIXR.</span></p>\n";
echo "                                                <p><span style=\"color: #808080;\">Mount ‘downloads’ (subdirectories will be automatically created), ‘movies’, ‘series’, ’music’, ‘comics’ and ‘books’ folders to a location with enough free disk space like a NAS, local/external harddrive, etc.</span></p>\n";
echo "                                                <p><span style=\"color: #808080;\">Use <a href=\"/webmin/mount/\" target=\"_blank\" rel=\"tooltip\" title=\"Default username and password: openflixr. Go to 'System - Disk and Network Filesystems'\">Webmin<sup> <i class=\"fa fa-external-link\" aria-hidden=\"true\" style=\"font-size:0.8em\"></i></sup></a> to make this easier. OpenFLIXR is case sensitive.</span></p>\n";
echo "                                                <br><p><center><span class=\"alert alert-info\">OpenFLIXR uses the following default directory structure</span></center></p><br>\n";
echo "                                                <center>\n";
echo "                                                    <p><span style=\"color: #808080;\">Use the <a href=\"http://www.openflixr.com/forum\" target=\"_blank\">forums</a> if you need help</span></p>\n";
echo "                                                </center>\n";
echo "                                                <br>\n";
echo "                                                <div style=\"padding-left: 0px;\" class=\"col-md-6 tooltip-wide\">\n";
echo "                                                    <div onclick=\"$('#downloads').toggle();\">\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Main downloads folder\"><span style=\"color: #808080;\">\n";
echo "                                                <a style=\"text-decoration: none;cursor: pointer;\"><i id=\"fac_573361a7db016\" class=\"fa fa-folder-o\"></i>\n";
echo "                                                /mnt/<b>downloads/... (click to open)</b></a></span></p>\n";
echo "                                                    </div>\n";
echo "                                                    <div class=\"collapse\" id=\"downloads\">\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"SABnzbd automatically picks up .nzb files placed here (also used for packages)\"><span style=\"color: #808080;\">\n";
echo "                                                &nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7dc060\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                blackholenzb\n";
echo "                                              </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"NZBget automatically picks up .nzb files placed here\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7dd1b7\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                blackholenzbget\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Completed misc. downloads are placed here\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7de197\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                complete\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Incompleted downloads\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7df24b\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                incomplete\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Completed but not processed Music\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7e02c9\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                music\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Completed and processed (by Headphones) Music are placed here\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7e12ec\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                musicready\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Temp folder\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7e2346\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                temp\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Finished but not processed Comics\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7e396d\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                tempcomics\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Finished but not processed TV Shows\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7e498d\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                tempseries\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Completed Torrents are placed here\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7e59f6\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                torrentcomplete\n";
echo "                                                </span></p>\n";
echo "                                                        <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"qBittorrent automatically picks up .torrent files placed here (also used for packages)\"><span style=\"color: #808080;\">&nbsp; &nbsp; &nbsp;\n";
echo "                                                <i id=\"fac_573361a7e69f9\" class=\"fa fa-folder-open-o\"></i>\n";
echo "                                                torrentwatch</span></p>\n";
echo "\n";
echo "                                                    </div>\n";
echo "\n";
echo "                                                    <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Completed Movies are placed here\"><span style=\"color: #808080;\">\n";
echo "<i id=\"fac_573361a7e7930\" class=\"fa fa-folder-o\"></i>\n";
echo "/mnt/<b>movies</b>\n";
echo "</span></p>\n";
echo "                                                    <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Completed TV Shows are placed here\"><span style=\"color: #808080;\">\n";
echo "<i id=\"fac_573361a7e897b\" class=\"fa fa-folder-o\"></i>\n";
echo "/mnt/<b>series</b>\n";
echo "</span></p>\n";
echo "                                                    <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"This folder can be used for Plex and Headphones to scan for music. Not mandatory\"><span style=\"color: #808080;\">\n";
echo "<i id=\"fac_573361a7e9984\" class=\"fa fa-folder-o\"></i>\n";
echo "/mnt/<b>music</b>\n";
echo "</span></p>\n";
echo "                                                    <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Completed Comics are placed here\"><span style=\"color: #808080;\">\n";
echo "<i id=\"fac_573361a7ead86\" class=\"fa fa-folder-o\"></i>\n";
echo "/mnt/<b>comics</b></span></p>\n";
echo "                                                    <p style=\"margin:0;\" rel=\"tooltip\" data-placement=\"right\" title=\"Completed Books are placed here\"><span style=\"color: #808080;\">\n";
echo "<i id=\"fac_573361a7ead88\" class=\"fa fa-folder-o\"></i>\n";
echo "/mnt/<b>books</b></span></p>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                    <div class=\"tab-pane\" id=\"network\">\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-12\">\n";
echo "                                                <h4 class=\"info-text\">Choose network configuration</h4>\n";
echo "                                            </div>\n";
echo "                                            <div class=\"row\">\n";
echo "                                                <div class=\"col-sm-10 col-sm-offset-1\">\n";
echo "                                                    <div class=\"col-sm-4 col-sm-offset-2\">\n";
echo "                                                        <div class=\"choice active\" data-toggle=\"wizard-radio\" rel=\"tooltip\" title=\"Automatic IP assigment. Choose DHCP if you're not sure what to choose\">\n";
echo "                                                            <label for=\"dhcp\">\n";
echo "                                                                <input type=\"radio\" name=\"networkconfig\" value=\"dhcp\" checked=\"checked\">\n";
echo "                                                                <div class=\"icon\" onclick=\"$('#collapseExample').hide();\">\n";
echo "                                                                    <i class=\"fa fa-magic\"></i>\n";
echo "                                                                </div>\n";
echo "                                                                DHCP</label>\n";
echo "                                                        </div>\n";
echo "                                                    </div>\n";
echo "                                                    <div class=\"col-sm-4\">\n";
echo "                                                        <div class=\"choice\" data-toggle=\"wizard-radio\" rel=\"tooltip\" title=\"Static IP assignment. Only choose when you know what you're doing\">\n";
echo "                                                            <label for=\"static\">\n";
echo "                                                                <input type=\"radio\" name=\"networkconfig\" value=\"static\">\n";
echo "                                                                <div class=\"icon\" onclick=\"$('#collapseExample').show();\">\n";
echo "                                                                    <i class=\"fa fa-wrench\"></i>\n";
echo "                                                                </div>\n";
echo "                                                                STATIC</label>\n";
echo "                                                        </div>\n";
echo "                                                    </div>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "                                            <div class=\"collapse\" id=\"collapseExample\">\n";
echo "                                                <div class=\"col-sm-5 col-sm-offset-1\">\n";
echo "                                                    <br>\n";
echo "                                                    <label>IP Address</label>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-sitemap\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input type=\"text\" class=\"form-control\" id=\"ip\" name=\"ip\" placeholder=\"E.g. 10.200.10.50\" required>\n";
echo "                                                    </div>\n";
echo "                                                </div>\n";
echo "                                                <div class=\"col-sm-5\">\n";
echo "                                                    <br>\n";
echo "                                                    <label>Subnet Mask</label>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-sitemap\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"subnet\" type=\"text\" class=\"form-control\" id=\"subnet\" placeholder=\"E.g. 255.255.255.0\" required>\n";
echo "                                                    </div>\n";
echo "                                                </div>\n";
echo "                                                <div class=\"col-sm-5 col-sm-offset-1\">\n";
echo "                                                    <br>\n";
echo "                                                    <label>Gateway</label>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-sitemap\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"gateway\" type=\"text\" class=\"form-control\" id=\"gateway\" placeholder=\"E.g. 10.200.10.1\" required>\n";
echo "                                                    </div>\n";
echo "                                                </div>\n";
echo "                                                <div class=\"col-sm-5\">\n";
echo "                                                    <br>\n";
echo "                                                    <label>DNS Server</label>\n";
echo "                                                    <div class=\"input-group\" rel=\"tooltip\" title=\"Pi-hole is used\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-sitemap\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"dns\" type=\"text\" class=\"form-control\" id=\"dns\" value=\"127.0.0.1\" readonly required>\n";
echo "                                                    </div>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "                                        </div>\n";
echo "                                        <br>\n";
echo "                                    </div>\n";
echo "\n";
echo "                                    <div class=\"tab-pane\" id=\"ssl\">\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-12\">\n";
echo "                                                <h4 class=\"info-text\">How do you want to access OpenFLIXR</h4>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"row\">\n";
echo "                                                <div class=\"col-sm-10 col-sm-offset-1\">\n";
echo "                                                    <div class=\"col-sm-4 col-sm-offset-2\">\n";
echo "                                                        <div class=\"choice active\" data-toggle=\"wizard-radio\" rel=\"tooltip\" title=\"Select this option if you want OpenFLIXR to be available only from your local network\">\n";
echo "                                                            <input type=\"radio\" name=\"letsencrypt\" value=\"off\" checked=\"checked\">\n";
echo "                                                            <div class=\"icon\" onclick=\"$('#remote').hide();\">\n";
echo "                                                                <i class=\"fa fa-home\"></i>\n";
echo "                                                            </div>\n";
echo "                                                            <label for=\"local\">LOCAL</label>\n";
echo "                                                        </div>\n";
echo "                                                    </div>\n";
echo "\n";
echo "                                                    <div class=\"col-sm-4\">\n";
echo "                                                        <div class=\"choice\" data-toggle=\"wizard-radio\" rel=\"tooltip\" title=\"Select this option if you want OpenFLIXR to be available from your local network and the Internet\">\n";
echo "                                                            <input type=\"radio\" name=\"letsencrypt\" value=\"on\">\n";
echo "                                                            <div class=\"icon\" onclick=\"$('#remote').show();\">\n";
echo "                                                                <i class=\"fa fa-cloud\"></i>\n";
echo "                                                            </div>\n";
echo "                                                            <label for=\"remote\">REMOTE</label>\n";
echo "                                                        </div>\n";
echo "                                                    </div>\n";
echo "\n";
echo "\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"collapse\" id=\"remote\">\n";
echo "\n";
echo "\n";
echo "                                                <div class=\"col-sm-7 col-sm-offset-3\">\n";
echo "                                                    <div class=\"form-group\">\n";
echo "                                                        <br>\n";
echo "                                                        <p><span style=\"color: #808080;\">Free secure remote access with </span><a href=\"https://letsencrypt.org\" target=\"_blank\">Let’s Encrypt</a>&nbsp;<span style=\"color: #808080;\">is enabled as soon as you've met all conditions below. Certificates are auto-renewed.<br></p>\n";
echo "\n";
echo "                                     <p><span style=\"color: #808080;\"><style>\n";
echo "                                     #fac_57324bf4abf31 {\n";
echo "                                     color: #808080;            }\n";
echo "                                     #fac_57324bf4abf31:hover {\n";
echo "                                     }\n";
echo "                                     </style>\n";
echo "                                     <i id=\"fac_57324bf4abf31\" class=\"fa fa-check-square-o\"></i>\n";
echo "                                     Register domain name</span>\n";
echo "                                                            <br>\n";
echo "                                                            <span style=\"color: #808080;\" rel=\"tooltip\" title=\"Both records should point to your public IP address, www. and without. I.e. www.example.com and example.com\"><style>\n";
echo "                                     #fac_57324bf4aca8a {\n";
echo "                                     color: #808080;            }\n";
echo "                                     #fac_57324bf4aca8a:hover {\n";
echo "                                     }\n";
echo "                                     </style>\n";
echo "                                     <i id=\"fac_57324bf4aca8a\" class=\"fa fa-check-square-o\"></i>\n";
echo "                                     Edit / add&nbsp;<a href=\"https://support.google.com/a/answer/2576578\" target=\"_blank\">A records</a> and point <b>both</b> to your public IP address</span>\n";
echo "                                                            <br>\n";
echo "                                                            <span style=\"color: #808080;\"><style>\n";
echo "                                     #fac_57324bf4ad906 {\n";
echo "                                     color: #808080;            }\n";
echo "                                     #fac_57324bf4ad906:hover {\n";
echo "                                     }\n";
echo "                                     </style>\n";
echo "                                     <i id=\"fac_57324bf4ad906\" class=\"fa fa-check-square-o\"></i>\n";
echo "                                     Forward port <b>443</b> (only!) on your router to local IP of OpenFLIXR</span>\n";
echo "                                                            <br>\n";
echo "                                                            <span style=\"color: #808080;\"><style>\n";
echo "                                     #fac_57324bf4aee2a {\n";
echo "                                     color: #808080;            }\n";
echo "                                     #fac_57324bf4aee2a:hover {\n";
echo "                                     }\n";
echo "                                     </style>\n";
echo "                                     <i id=\"fac_57324bf4aee2a\" class=\"fa fa-check-square-o\"></i>\n";
echo "                                     Enter domainname and e-mail address below</span></p>\n";
echo "                                                        <div>\n";
echo "                                                            <label>Domain (required to obtain certificate)</label>\n";
echo "                                                            <div class=\"input-group\">\n";
echo "                                                                <span style=\"color:#808080\" class=\"input-group-addon\">www.</i></span>\n";
echo "                                                                <input name=\"domainname\" type=\"text\" class=\"form-control\" id=\"domainname\" placeholder=\"example.com\" required rel=\"tooltip\" title=\"Let's Encrypt certificate will contain both base domain and with www.\">\n";
echo "                                                            </div>\n";
echo "                                                        </div>\n";
echo "                                                        <br>\n";
echo "                                                        <div>\n";
echo "                                                            <label>E-mail address (required for lost key recovery)</label>\n";
echo "                                                            <div class=\"input-group\">\n";
echo "                                                                <span style=\"color:#808080\" class=\"input-group-addon\">&nbsp&nbsp&nbsp<i class=\"fa fa-envelope-o\" aria-hidden=\"true\">&nbsp&nbsp&nbsp</i></span>\n";
echo "                                                                <input name=\"email\" type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"somebody@example.com\" required>\n";
echo "                                                            </div>\n";
echo "                                                        </div>\n";
echo "                                                    </div>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "\n";
echo "                                    <div class=\"tab-pane\" id=\"usenet\">\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-12\">\n";
echo "                                                <h4 class=\"info-text\">Usenet provider</h4>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\">\n";
echo "                                                <label>Description</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-pencil\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"usenetdescription\" type=\"text\" class=\"form-control\" id=\"usenetdescription\" placeholder=\"Super Usenet\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5\">\n";
echo "                                                <label>Servername</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-server\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"usenetservername\" type=\"text\" class=\"form-control\" id=\"usenetservername\" placeholder=\"news.example.com\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\">\n";
echo "                                                <br>\n";
echo "                                                <label>Username</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"usenetusername\" type=\"text\" class=\"form-control\" id=\"usenetusername\" placeholder=\"username\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5\">\n";
echo "                                                <br>\n";
echo "                                                <label>Password</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-lock\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"usenetpassword\" type=\"password\" class=\"form-control\" id=\"usenetpassword\" placeholder=\"password\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\">\n";
echo "                                                <br>\n";
echo "                                                <label>Port</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-circle-o\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"usenetport\" type=\"number\" class=\"form-control\" id=\"usenetport\" value=\"119\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5\">\n";
echo "                                                <br>\n";
echo "                                                <label>Number of threads</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-wrench\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"usenetthreads\" type=\"number\" class=\"form-control\" id=\"usenetthreads\" value=\"4\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\">\n";
echo "                                                <br>\n";
echo "                                                <label>SSL</label>\n";
echo "                                                <div class=\"input-group col-xs-4\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-user-secret\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <select name=\"usenetssl\" id=\"usenetssl\" class=\"form-control\">\n";
echo "                                                        <option value=\"0\" selected>No</option>\n";
echo "                                                        <option value=\"1\">Yes</option>\n";
echo "                                                    </select>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                        </div>\n";
echo "                                        <br>\n";
echo "                                    </div>\n";
echo "                                    <div class=\"tab-pane\" id=\"newznab\">\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-12\">\n";
echo "                                                <h4 class=\"info-text\">Newznab provider</h4>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\">\n";
echo "                                                <label>Description</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-pencil\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"newznabprovider\" type=\"text\" class=\"form-control\" id=\"newznabprovider\" placeholder=\"NZB Planet\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5\">\n";
echo "                                                <label>Newznab URL</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-link\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"newznaburl\" type=\"url\" class=\"form-control\" id=\"newznaburl\" placeholder=\"http://nzb.example.com\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\">\n";
echo "                                                <br>\n";
echo "                                                <label>Newznab API</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-key\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"newznabapi\" type=\"text\" class=\"form-control\" id=\"newznabapi\" placeholder=\"apikey\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "\n";
echo "                                    <div class=\"tab-pane\" id=\"modules\">\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-12\">\n";
echo "                                                <h4 class=\"info-text\">Select modules</h4>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-md-4\">\n";
echo "                                                <br>\n";
echo "                                                <label class=\"col-md-offset-1\">TV Shows Downloader</label>\n";
echo "                                                <div class=\"input-group col-md-10 col-md-offset-1\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-television\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <select name=\"tvshowdl\" id=\"tvshowdl\" class=\"form-control\">\n";
echo "                                                        <option value=\"sickrage\" selected>SickRage (recommended)</option>\n";
echo "                                                        <option value=\"sonarr\">Sonarr</option>\n";
echo "                                                    </select>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-md-4\">\n";
echo "                                                <br>\n";
echo "                                                <label class=\"col-md-offset-1\">NZB Downloader</label>\n";
echo "                                                <div class=\"input-group col-md-10 col-md-offset-1\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-download\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <select name=\"nzbdl\" id=\"nzbdl\" class=\"form-control\">\n";
echo "                                                        <option value=\"sabnzbd\" selected>SABnzbd (recommended)</option>\n";
echo "                                                        <option value=\"nzbget\">NZBget</option>\n";
echo "                                                    </select>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-md-4\">\n";
echo "                                                <br>\n";
echo "                                                <label class=\"col-md-offset-1\">Mopidy</label>\n";
echo "                                                <div class=\"input-group col-md-10 col-md-offset-1\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-music\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <select name=\"mopidy\" id=\"mopidy\" class=\"form-control\">\n";
echo "                                                        <option value=\"enabled\" selected>Enabled</option>\n";
echo "                                                        <option value=\"disabled\">Disabled</option>\n";
echo "                                                    </select>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-md-4\">\n";
echo "                                                <br>\n";
echo "                                                <label class=\"col-md-offset-1\">Home-Assistant</label>\n";
echo "                                                <div class=\"input-group col-md-10 col-md-offset-1\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-home\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <select name=\"hass\" id=\"hass\" class=\"form-control\">\n";
echo "                                                        <option value=\"enabled\" selected>Enabled</option>\n";
echo "                                                        <option value=\"disabled\">Disabled</option>\n";
echo "                                                    </select>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-md-4\" rel=\"tooltip\" title=\"ntopNG is CPU intensive. Although extremely cool and useful, enable only if you need/want this. \">\n";
echo "                                                <br>\n";
echo "                                                <label class=\"col-md-offset-1\">ntopNG</label>\n";
echo "                                                <div class=\"input-group col-md-10 col-md-offset-1\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-sitemap\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <select name=\"ntopng\" id=\"ntopng\" class=\"form-control\">\n";
echo "                                                        <option value=\"enabled\">Enabled</option>\n";
echo "                                                        <option value=\"disabled\" selected>Disabled</option>\n";
echo "                                                    </select>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "\n";
echo "                                    <div class=\"tab-pane\" id=\"login\">\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-12\">\n";
echo "                                                <h4 class=\"info-text\">Set new global password</h4>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-4 col-sm-offset-4\">\n";
echo "                                                <div class=\"form-group\">\n";
echo "                                                    <center><label class=\"alert alert-success\">Username is openflixr</label></center>\n";
echo "                                                    <br>\n";
echo "                                                    <label>Password</label>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-lock\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"password\" type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"password\" required>\n";
echo "                                                    </div>\n";
echo "                                                    <div class=\"form-group\">\n";
echo "                                                        <br>\n";
echo "                                                        <label>Confirm</label>\n";
echo "                                                        <div class=\"input-group\">\n";
echo "                                                            <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-lock\" aria-hidden=\"true\"></i></span>\n";
echo "                                                            <input name=\"confirm_password\" type=\"password\" class=\"form-control\" id=\"confirm_password\" placeholder=\"password\" required>\n";
echo "                                                        </div>\n";
echo "                                                    </div>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "\n";
echo "                                    <div class=\"tab-pane\" id=\"extra\">\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-12\">\n";
echo "                                                <h4 class=\"info-text\">Optional settings</h4>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\" rel=\"tooltip\" title=\"Headphones VIP account is used in Headphones to find better Music results\">\n";
echo "                                                <label><a href=\"https://headphones.codeshy.com/vip/\" target=\"_blank\">Headphones VIP username</label></a>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"headphonesuser\" type=\"text\" class=\"form-control\" id=\"headphonesuser\" placeholder=\"username\">\n";
echo "                                                    </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5\">\n";
echo "                                                <label>Headphones VIP password</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-lock\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"headphonespass\" type=\"password\" class=\"form-control\" id=\"headphonespass\" placeholder=\"password\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\" rel=\"tooltip\" title=\"AniDB account is used in SickRage to find better Anime results\">\n";
echo "                                                <br>\n";
echo "                                                <label><a href=\"http://anidb.net\" target=\"_blank\">AniDB username</label></a>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"anidbuser\" type=\"text\" class=\"form-control\" id=\"anidbuser\" placeholder=\"username\">\n";
echo "                                                    </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5\">\n";
echo "                                                <br>\n";
echo "                                                <label>AniDB password</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-lock\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"anidbpass\" type=\"password\" class=\"form-control\" id=\"anidbpass\" placeholder=\"password\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\" rel=\"tooltip\" title=\"Spotify account is needed in mopidy/mopify\">\n";
echo "                                                <br>\n";
echo "                                                <label><a href=\"http://www.spotify.com\" target=\"_blank\">Spotify username</label></a>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"spotuser\" type=\"text\" class=\"form-control\" id=\"spotuser\" placeholder=\"username\">\n";
echo "                                                    </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5\">\n";
echo "                                                <br>\n";
echo "                                                <label>Spotify password</label>\n";
echo "                                                <div class=\"input-group\">\n";
echo "                                                    <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-lock\" aria-hidden=\"true\"></i></span>\n";
echo "                                                    <input name=\"spotpass\" type=\"password\" class=\"form-control\" id=\"spotpass\" placeholder=\"password\">\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5 col-sm-offset-1\" rel=\"tooltip\" title=\"IMDB public watchlist URL is used in CouchPotato to automatically download movies added to your watchlist\">\n";
echo "                                                <br>\n";
echo "                                                <label><a href=\"http://www.imdb.com\" target=\"_blank\">IMDB public watchlist URL</label></a>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-link\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"imdb\" type=\"url\" class=\"form-control\" id=\"imdb\" placeholder=\"http://rss.imdb.com/user/ur12345678/watchlist\">\n";
echo "                                                    </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                            <div class=\"col-sm-5\" rel=\"tooltip\" title=\"Comic Vine API key is used in Mylar to find better Comic results\">\n";
echo "                                                <br>\n";
echo "                                                <label><a href=\"http://comicvine.gamespot.com\" target=\"_blank\">Comic Vine API key</label></a>\n";
echo "                                                    <div class=\"input-group\">\n";
echo "                                                        <span style=\"color:#808080\" class=\"input-group-addon\"><i class=\"fa fa-key\" aria-hidden=\"true\"></i></span>\n";
echo "                                                        <input name=\"comicvine\" type=\"text\" class=\"form-control\" id=\"plex\" placeholder=\"apikey\">\n";
echo "                                                    </div>\n";
echo "                                            </div>\n";
echo "\n";
echo "                                        </div>\n";
echo "                                        <br>\n";
echo "                                    </div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "                                    <div class=\"tab-pane\" id=\"finish\" name=\"messagebox\">\n";
echo "                                        <h4 class=\"info-text\">Plex integration</h4>\n";
echo "                                        <div class=\"row\">\n";
echo "                                            <div class=\"col-sm-10 col-sm-offset-1\">\n";
echo "                                                <p><span style=\"color: #808080;\">Tight integration with <a href=\"https://plex.tv\" target=\"_blank\">Plex</a> makes OpenFLIXR even more powerful. For optimum performance, you should configure the following applications with your Plex account. Click buttons to go directly to those settings.</span></p>\n";
echo "                                                <p><span style=\"color: #808080;\">Use the old password to login, the new password is effective when OpenFLIXR setup has been completed.</span></p>\n";
echo "                                                <br>\n";
echo "                                                <center>\n";
echo "                                                    <a style=\"width: 35%;\" href=\"/couchpotato/settings/notifications/\" target=\"_blank\" class=\"btn btn-block btn-sm btn-info btn-fill\">CouchPotato</a>\n";
echo "                                                    <a style=\"width: 35%;\" href=\"/sickrage/config/notifications/\" target=\"_blank\" class=\"btn btn-block btn-sm btn-info btn-fill\">SickRage</a>\n";
echo "                                                    <a style=\"width: 35%;\" href=\"/plexpy\" target=\"_blank\" class=\"btn btn-block btn-sm btn-info btn-fill\">PlexPy</a>\n";
echo "                                                    <a style=\"width: 35%;\" href=\"/request/admin/authentication\" target=\"_blank\" class=\"btn btn-block btn-sm btn-info btn-fill\">PlexRequests</a>\n";
echo "                                                    <a style=\"width: 35%;\" href=\"/htpc/settings/#plex\" target=\"_blank\" class=\"btn btn-block btn-sm btn-info btn-fill\">HTPC Manager</a></center>\n";
echo "                                                <br>\n";
echo "                                                <br>\n";
echo "                                                <h4 style=\"margin: 0;\" class=\"info-text\">If you're sure all settings are correct, click <b>finish</b> to continue</h4>\n";
echo "                                                <h4 class=\"info-text\">Setup will take a while, system will reboot when done</h4>\n";
echo "                                            </div>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "                                </div>\n";
echo "                                <div class=\"wizard-footer\">\n";
echo "                                    <div class=\"pull-right\">\n";
echo "                                        <input type='button' class='btn btn-next btn-fill btn-success btn-wd btn-sm' name='next' value='Next' />\n";
echo "                                        <input type='submit' class='btn btn-finish btn-fill btn-success btn-wd btn-sm' name='finish' value='Finish' />\n";
echo "\n";
echo "                                    </div>\n";
echo "                                    <div class=\"pull-left\">\n";
echo "                                        <input type='button' class='btn btn-previous btn-fill btn-default btn-wd btn-sm' name='previous' value='Previous' />\n";
echo "                                    </div>\n";
echo "                                    <div class=\"clearfix\"></div>\n";
echo "                                </div>\n";
echo "                            </form>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <!-- wizard container -->\n";
echo "\n";
echo "</body>\n";
echo "\n";
echo "<script src=\"js/jquery-1.10.2.js\" type=\"text/javascript\"></script>\n";
echo "<script src=\"js/bootstrap.min.js\" type=\"text/javascript\"></script>\n";
echo "<script src=\"js/jquery.bootstrap.wizard.js\" type=\"text/javascript\"></script>\n";
echo "<script src=\"js/jquery.validate.min.js\"></script>\n";
echo "<script src=\"js/wizard.js\"></script>\n";
echo "<script src=\"js/custom.js\"></script>\n";
echo "\n";
echo "</html>\n";
echo "\n";
?>
